version: 0.0
os: linux
files:
  - source: /
    destination: /sample-app
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
